# This is a basic workflow that is manually triggered

name: front Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: fangchenjia/rf4-community-front-admin:latest
      - name: Deploy to Docker
        uses: appleboy/ssh-action@master
        with:
          host: 110.42.213.115
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop rf4-community-front-admin || true
            docker rm rf4-community-front-admin || true
            docker rmi fangchenjia/rf4-community-front-admin || true
            docker pull fangchenjia/rf4-community-front-admin
            docker run -d -p 8083:80 --name rf4-community-front-admin fangchenjia/rf4-community-front-admin   -e VG_BASE_URL=/api-admin

  
